### ISSUE TITLE
Double THE

### ISSUE THREAD

**Issue by Adarma** [cfsamson/articles-atomics-in-rust#1]
> Ok, so when we use the methods on atomics like fetch_addon AtomicUsize it actually the the assembly would instead look something like (an AT&T dalect) lock addq ..., ...instead of addq ..., ...which we'd normally expect.

There is a double "the" in that sentence, but even without it, it doesn't make sense to me.

**Comment by cfsamson** [comment]
Thanks. A part of that sentence went missing it seems. It's corrected now and changed to:

> Ok, so when we use the methods on atomics like fetch_add on AtomicUsize it actually changes the instructions we use to add the two numbers on the CPU. The assembly would instead look something like (an AT&T dalect) lock addq ..., ...instead of addq ..., ...which we'd normally expect.

Thanks for reporting.
