### ISSUE TITLE
Rust supports more than AtomicUsize

### ISSUE THREAD

**Issue by programmerjake** [cfsamson/articles-atomics-in-rust#3]
I noticed at the end that you said Rust only supports `usize`-sized atomics, which is incorrect: Rust's standard library supports all of `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, and `i64` since v1.34 and `usize`, `isize`, `bool`, and `*mut T` since v1.0.

See [`AtomicU8`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicU8.html)

Btw, really liked your article! You might find reading about TileLink interesting, since it is an open-source cache-coherent memory interface used in a lot of RISC-V computers.

**Comment by cfsamson** [comment]
Ah, I see how that can sound wrong now. 
You're thinking about the sentence:
> Presumably this is the major reason that all atomic operations is limited to usize sized data.

A bad sentence on my part, I meant that the datatype was limited to usize-sized data, not that it's the only type :) If I'm not mistaken, `AtomicBool` is also a byte-sized datatype.

I rewrote it to:
> Presumably this is the major reason that all atomic operations is limited to data types smaller or equal to `usize` sized data.

Glad to hear you enjoyed it though. TileLink looks very interesting, thanks for pointing me to it!

**Comment by programmerjake** [comment]
`AtomicU64` is bigger than `usize` on 32-bit architectures, i386 in particular.

**Comment by cfsamson** [comment]
I seem to have mixed up bits and bytes in my line of reasoning there. I just removed the whole sentence since, honestly, it doesn't make sense in the context of cache line sizes.

**Comment by programmerjake** [comment]
Looks good to me!
